
package GUI;

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        //INICIALIZANDO VENTANA LOGIN 
        Login lo = new Login(this, true); // 
        lo.setVisible(true);
        
        initComponents();
        
        //FUNCION PARA CENTRAR VENTANA
        this.setLocationRelativeTo(null);
        
        //
        Inicio inicio = new Inicio();
        JpContenedor.removeAll();
        JpContenedor.setLayout(new java.awt.BorderLayout()); 
        JpContenedor.add(inicio, java.awt.BorderLayout.CENTER);
        JpContenedor.revalidate();
        JpContenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        JpContenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mbSistema = new javax.swing.JMenu();
        miInicio = new javax.swing.JMenuItem();
        miCerrarSesion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miEmpleados = new javax.swing.JMenuItem();
        miTurnos = new javax.swing.JMenuItem();
        miRoles = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miMarcarAsistencias = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miSolicitudes = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu6.setText("jMenu6");

        jMenuItem10.setText("jMenuItem10");

        jMenuItem11.setText("jMenuItem11");

        jMenuItem12.setText("jMenuItem12");

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        JpContenedor.setBackground(new java.awt.Color(31, 41, 55));
        JpContenedor.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo 2.png"))); // NOI18N

        javax.swing.GroupLayout JpContenedorLayout = new javax.swing.GroupLayout(JpContenedor);
        JpContenedor.setLayout(JpContenedorLayout);
        JpContenedorLayout.setHorizontalGroup(
            JpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpContenedorLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        JpContenedorLayout.setVerticalGroup(
            JpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpContenedorLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        mbSistema.setBackground(new java.awt.Color(31, 41, 55));
        mbSistema.setForeground(new java.awt.Color(31, 41, 55));
        mbSistema.setText("Sistema");
        mbSistema.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miInicio.setText("Inicio");
        miInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInicioActionPerformed(evt);
            }
        });
        mbSistema.add(miInicio);

        miCerrarSesion.setText("Cerrar Sesión");
        miCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCerrarSesionActionPerformed(evt);
            }
        });
        mbSistema.add(miCerrarSesion);

        jMenuBar2.add(mbSistema);

        jMenu2.setBackground(new java.awt.Color(31, 41, 55));
        jMenu2.setText("Gestión");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miEmpleados.setText("Empleados");
        miEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmpleadosActionPerformed(evt);
            }
        });
        jMenu2.add(miEmpleados);

        miTurnos.setText("Turnos");
        miTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTurnosActionPerformed(evt);
            }
        });
        jMenu2.add(miTurnos);

        miRoles.setText("Roles");
        miRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRolesActionPerformed(evt);
            }
        });
        jMenu2.add(miRoles);

        jMenuBar2.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(31, 41, 55));
        jMenu3.setForeground(new java.awt.Color(31, 41, 55));
        jMenu3.setText("Asistencia");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miMarcarAsistencias.setText("Marcar Asistencias");
        miMarcarAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMarcarAsistenciasActionPerformed(evt);
            }
        });
        jMenu3.add(miMarcarAsistencias);

        jMenuBar2.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(31, 41, 55));
        jMenu4.setForeground(new java.awt.Color(31, 41, 55));
        jMenu4.setText("Permisos");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miSolicitudes.setText("Solicitudes");
        miSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSolicitudesActionPerformed(evt);
            }
        });
        jMenu4.add(miSolicitudes);

        jMenuBar2.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(31, 41, 55));
        jMenu5.setForeground(new java.awt.Color(31, 41, 55));
        jMenu5.setText("Reportes");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem8.setText("Generar Reporte");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCerrarSesionActionPerformed
        //Oculta ventana principal
        this.setVisible(false); 
        
        Login lo = new Login(this, true); // this = tu JFrame principal
        lo.setVisible(true);
        //Muestra ventana principal
        this.setVisible(true); 
    }//GEN-LAST:event_miCerrarSesionActionPerformed

    private void miInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInicioActionPerformed
        // TODO add your handling code here:
        //Inicio inicio = new Inicio();
        Inicio inicio = new Inicio();

        JpContenedor.removeAll();
        JpContenedor.setLayout(new java.awt.BorderLayout()); 
        JpContenedor.add(inicio, java.awt.BorderLayout.CENTER);
        JpContenedor.revalidate();
        JpContenedor.repaint();
    }//GEN-LAST:event_miInicioActionPerformed

    private void miEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEmpleadosActionPerformed
        // TODO add your handling code here:
        Empleado empleado = new Empleado();

        JpContenedor.removeAll();
        JpContenedor.setLayout(new java.awt.BorderLayout()); 
        JpContenedor.add(empleado, java.awt.BorderLayout.CENTER);
        JpContenedor.revalidate();
        JpContenedor.repaint();
    }//GEN-LAST:event_miEmpleadosActionPerformed

    private void miMarcarAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMarcarAsistenciasActionPerformed
        // TODO add your handling code here:
        Marcar_Asistencia marcar_asistenica = new Marcar_Asistencia();

        JpContenedor.removeAll();
        JpContenedor.setLayout(new java.awt.BorderLayout()); 
        JpContenedor.add(marcar_asistenica, java.awt.BorderLayout.CENTER);
        JpContenedor.revalidate();
        JpContenedor.repaint();
        
    }//GEN-LAST:event_miMarcarAsistenciasActionPerformed

    private void miTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTurnosActionPerformed
         
        Turno turno = new Turno();

        JpContenedor.removeAll();
        JpContenedor.setLayout(new java.awt.BorderLayout()); 
        JpContenedor.add(turno, java.awt.BorderLayout.CENTER);
        JpContenedor.revalidate();
        JpContenedor.repaint();
    }//GEN-LAST:event_miTurnosActionPerformed

    private void miSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSolicitudesActionPerformed
        // TODO add your handling code here:
        Permiso permiso = new Permiso();

        JpContenedor.removeAll();
        JpContenedor.setLayout(new java.awt.BorderLayout()); 
        JpContenedor.add(permiso, java.awt.BorderLayout.CENTER);
        JpContenedor.revalidate();
        JpContenedor.repaint();
        
        
    }//GEN-LAST:event_miSolicitudesActionPerformed

    private void miRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRolesActionPerformed
        // TODO add your handling code here:
        
        Roles roles = new Roles();

        JpContenedor.removeAll();
        JpContenedor.setLayout(new java.awt.BorderLayout()); 
        JpContenedor.add(roles, java.awt.BorderLayout.CENTER);
        JpContenedor.revalidate();
        JpContenedor.repaint();
        
        
        
    }//GEN-LAST:event_miRolesActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        Generar_Reporte_Asistencia reporte = new Generar_Reporte_Asistencia();

        JpContenedor.removeAll();
        JpContenedor.setLayout(new java.awt.BorderLayout()); 
        JpContenedor.add(reporte, java.awt.BorderLayout.CENTER);
        JpContenedor.revalidate();
        JpContenedor.repaint();
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpContenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenu mbSistema;
    private javax.swing.JMenuItem miCerrarSesion;
    private javax.swing.JMenuItem miEmpleados;
    private javax.swing.JMenuItem miInicio;
    private javax.swing.JMenuItem miMarcarAsistencias;
    private javax.swing.JMenuItem miRoles;
    private javax.swing.JMenuItem miSolicitudes;
    private javax.swing.JMenuItem miTurnos;
    // End of variables declaration//GEN-END:variables
}
